language: node_js

branches:
  only:
    - master

node_js:
  - "14"
  - "13"
  - "12"
  - "10"
  - "8"

before_script:
  - npm install

script:
  - npm run lint
  - istanbul cover ./node_modules/mocha/bin/_mocha test/keys.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
